export enum ActionTypesCoffe {
  INCREASE_QUANTITY = 'INCREASE_QUANTITY',
  DECREASE_QUANTITY = 'DECREASE_QUANTITY',
  ADD_NEW_ORDER_COFFE = 'ADD_NEW_ORDER_COFFE',
  DELETE_COFFE = 'DELETE_COFFE',
  ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS',
  RESET_COFFES = 'RESET_COFFES',
}
